### ISSUE TITLE
Is the value of the num_frame in Video Transformer fixed or not

### ISSUE THREAD

**Issue by Claire874** [SforAiDl/vformer#102]
Thanks for the great work in ViViT model 2.
Is the value of the num_frame fixed or not? Or does the model process each frame one by one?

**Comment by NeelayS** [comment]
Tagging @abhi-glitchhg who is better suited to help you with this.

**Comment by abhi-glitchhg** [comment]
Hey @Claire874 , glad you find this repo useful. 


> Is the value of the num_frame fixed or not

Yes, the value for a particular model will be fixed.  Passing down a video with different `num_frames` will result in dimensionality errors as we add the positional embeddings to the token embeddings. and dimensions of the positional embeddings are dependent on the `num_frames`.


https://github.com/SforAiDl/vformer/blob/b0370f9bda23d9da9fee5c14eaa5137eed936e0d/vformer/models/classification/vivit.py#L83-L86

https://github.com/SforAiDl/vformer/blob/b0370f9bda23d9da9fee5c14eaa5137eed936e0d/vformer/models/classification/vivit.py#L133




>  does the model process each frame one by one

No, the ViViT model doesn't process the frames one by one.  There are two ways of converting video into Embeddings 
1) Union Sampling Method 
![image](https://user-images.githubusercontent.com/72816663/224934277-3fe92039-adf3-4b7d-bfdd-9b49323606d4.png)

2) Tubelet Embeddings 
![image](https://user-images.githubusercontent.com/72816663/224934386-5c3dc245-c0af-4112-b232-090774051a1c.png)


For a single forward pass, both methods consider videoes of length `num_frames` (Or a video of length T in the above diagrams.) x. 

 

I hope I've answered your question. Let me know. 
Thanks!

**Comment by abhi-glitchhg** [comment]
In the [paper](https://arxiv.org/abs/2103.15691)  authors have done ablation studies with varying the number of input frames. You might want to go through that as well. 
 
![image](https://user-images.githubusercontent.com/72816663/224939588-16df8d49-00c6-4003-91fe-73cbfe0d5af5.png)

**Comment by Claire874** [comment]
Thanks for the detailed response, which is very helpful to me.

**Comment by Claire874** [comment]
For the different sequence lengths, is it ok to do the padding and mask padding to them?
Is there any available code in vformer? 👍

**Comment by abhi-glitchhg** [comment]
Zero padding or video interpolations could be the solution for your problem; Or instead of considering all frames, consider the views as mentioned in the ablation studies. In this way, you would have control over the number of frames/views, and it would reduce the memory footprints. Sadly we don't have the code for the above operations in vformer. [Scenic- official JAX implementation](https://github.com/google-research/scenic/tree/main/scenic/projects/vivit) might have code for the above operations in `data/` directory. (sorry for redirecting you to jax codebase :) )

**Comment by NeelayS** [comment]
@Claire874 I'll close this issue now. If you have any further questions, please feel free to re-open or create another issue.
