### ISSUE TITLE
Add sharpness-aware optimizer

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/vformer#11]
[This paper](https://arxiv.org/abs/2106.01548) describes how promoting smoothness with a recently proposed sharpness-aware optimizer substantially improves the performance of ViTs.

It would be good to have an implementation of this optimizer in our library. It would fit in the `functional` module.

A couple of PyTorch implementations are [here](https://github.com/moskomule/sam.pytorch/blob/main/sam.py) and [here](https://github.com/davda54/sam/blob/main/sam.py).

**Comment by nitish22066** [comment]
I would like to take up this issue

**Comment by NeelayS** [comment]
Let's use the implementation in the second link.
