### ISSUE TITLE
[Paper] ViViT: A Video Vision Transformer

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/vformer#26]
- Link: [https://arxiv.org/abs/2103.15691](https://arxiv.org/abs/2103.15691)

**Comment by abhi-glitchhg** [comment]
Can i try this one?
Original code is in JAX, but I will refer to this repo - https://github.com/rishikksh20/ViViT-pytorch

**Comment by NeelayS** [comment]
Yeah, sure!
