### ISSUE TITLE
Restructuring AbsolutePositionEmbedding class

### ISSUE THREAD

**Issue by abhi-glitchhg** [SforAiDl/vformer#42]
AbsolutePositionEmbedding class was structured specifically for the PVT, but we can use it in other models too if we re-structure it properly, it should also support sinusoidal position embedding or a separate class for Sinusoidal embedding also works.

**Comment by NeelayS** [comment]
Should I assign this to you since you are the best equipped to take it up?

**Comment by abhi-glitchhg** [comment]
sure
