### ISSUE TITLE
[Paper] Vision Transformers for Dense Prediction

### ISSUE THREAD

**Issue by NeelayS** [SforAiDl/vformer#5]
* Link: https://arxiv.org/abs/2103.13413

**Comment by gchhablani** [comment]
@NeelayS Can I take this up?

**Comment by NeelayS** [comment]
@gchhablani Sure! 
(Sorry for the late reply)

**Comment by NeelayS** [comment]
Hi @gchhablani, just wanted to check whether you are working on this. Thanks.

**Comment by abhi-glitchhg** [comment]
hey @gchhablani,  are you working on this issue?
If you are not, then I can try implementing this.

**Comment by NeelayS** [comment]
Hi @gchhablani, we would like to have this paper implemented before making the first release of the library (which we plan to do soon), so I'll be transferring this issue to Abhijit. I'm really sorry for any inconvenience caused.
