### ISSUE TITLE
Add doc strings to Vanilla VIT implementation

### ISSUE THREAD

**Issue by abhi-glitchhg** [SforAiDl/vformer#8]

**Comment by NeelayS** [comment]
Let's use [Numpy-style docstrings](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html#example-numpy) for this and all other code from now onwards.

**Comment by abhi-glitchhg** [comment]
If Nobody takes this till sunday; ill do this too.

**Comment by aditya-agrawal-30502** [comment]
i can take up this issue if its open

**Comment by abhi-glitchhg** [comment]
I'm taking this.
